services:
  - type: web
    name: rcps-valuation-docker
    runtime: docker
    region: singapore
    plan: free
    rootDir: rcps_valuation
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_USER
        value: admin
      - key: APP_PASSWORD
        sync: false
    healthCheckPath: /healthz
    autoDeploy: true
