domestic_locations:
  - 서울
  - 부산
  - 대구
  - 인천
  - 광주
  - 대전
  - 울산
  - 세종
  - 강남
  - 종로
  - 역삼
  - 여의도
  - 잠실
  - 신촌
  - 서초
  - 성수
  - 마포
  - 송파
  - 강북
  - 영등포
  - 분당
  - 판교
  - 일산
  - 수원
  - 용인
  - 성남
  - 화성
  - 청주
  - 천안
  - 전주
  - 광주광역
  - 창원
  - 포항
  - 제주
